# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: nandy
  password: nandy
  host: localhost

development:
  <<: *default
  database: prompt_finder

test:
  <<: *default
  database: prompt_finder

production:
  <<: *default
  database: prompt_finder
  username: nandy
  password: nandy
  host: localhost

